<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<?php //echo $this->jQuery(); ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php  echo $this->headTitle(); ?>

<?php  echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript();?>

<script type="text/javascript">
    // 01 Config variables locales.
    var __PATH_IMG ="<?php echo PATH_IMG; ?>"; //__PATH_RESOURCES_IMG
    console.log('__PATH_IMG',__PATH_IMG);


    // 02 Config Ext.js
    Ext.Loader.setConfig({ 
      enabled: true  
    }); 
    // Ext.onReady(function(){
    //     Ext.MessageBox.confirm('Confirm', 'Welcome your System Lab?', 'functionAction');
    // });
</script>
<!-- <script type="text/javascript" src="/scripts/security.js"></script>
 -->
<!-- LOAD  -->
<!-- <script type="text/javascript" src="/scripts/basic/functions_basic.js"></script>
<script type="text/javascript" src="/scripts/basic/panel_modules.js"></script>
<script type="text/javascript" src="/scripts/basic/init_module.js"></script>
 -->

</head>
<body id="docbody">
<?php 
    echo $this->layout()->content;
?> 
</body>
</html>
